<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $popular = [
            'Chocolate Milkshake',
            'Oreo Milkshake',
            'Falooda Milkshake',
            'Cold Coffee',
            'Jigarthanda',
            'Pani Puri',
            'Jalebi',
            'Mysore Pak',
            'Rasagulla',
            'Rasamalai',
            'Bele Holige',
            'Paneer Butter Masala',
        ];

        $menu = [
            'Milkshakes' => [
                'Almond Milkshake',
                'Anjur Milkshake',
                'Badam Milk',
                'Black Current Milkshake',
                'Blue Berry Milkshake',
                'Butter Scotch Milkshake',
                'Chocolate Milkshake',
                'Cold Coffee',
                'Cream Vanilla',
                'Dry Fruit Milkshake',
                'Falooda Milkshake',
                'Gulkand Milkshake',
                'Kesar Pista Badam',
                'Litchi Milkshake',
                'Litchi Gulkhand Milkshake',
                'Litchi with Strawberry Pulp',
                'Milk Shake Cocktail',
                'Nannari Milkshake',
                'Oreo Milkshake',
                'Pista Badam',
                'Pista Milkshake',
                'Pulpy Litchi Milkshake',
                'Pulpy Strawberry',
                'Rose Milkshake',
                'Sandal Wood Milkshake',
                'Sharjah Milkshake',
                'Strawberry with Pulp',
                'Tutty Fruity Milkshake',
                'Vanilla Milkshake',
                'Butter Fruit Milkshake (Seasonal)',
                'Carrot Milkshake',
                'Green Apple Milkshake',
                'Jack Fruit Milkshake (Seasonal)',
                'Kiwi Milkshake',
                'Mango Milkshake',
                'Custard Apple Milkshake (Seasonal)',
                'Sapota Milkshake (Seasonal)',
            ],
            'Fresh Fruit Juices' => [
                'Aam Panna',
                'Chilli Mango',
                'Grape Cocktail',
                'Grape Juice',
                'Guava Juice',
                'Kokum Juice',
                'Musk Melon Juice',
                'Pineapple Juice',
                'Pomegranate Juice',
                'Pudina Lime Juice',
                'Pulpy Grape',
                'Pulpy Orange Punch',
                'Sugar Cane Juice',
                'Water Melon Juice',
            ],
            'Fresh Fruit Fusion' => [
                'Anar Pineapple',
                'Barley Punch',
                'Blue Lagoon',
                'Crazy Punch',
                'Fruit Punch',
                'Fruit Punch Gold',
                'Jal Jeera',
                'Kiwi Punch',
                'Kokum Juice',
                'Mix Fruit Juice',
                'Nannari Juice',
                'Palak Pudina Juice',
                'Pineapple Tulsi',
                'Pudina Pineapple',
                'Ragi Punch',
                'Red Blast',
                'White Blast',
            ],
            'Coffee' => [
                'Cold Coffee',
                'Irish Cold Coffee',
                'Rich Coffee',
            ],
            'Hot Drinks' => [
                'Hot Chocolate',
                'Hot Badam',
                'Hot Pista',
                'Hot Dry Fruit Drink',
            ],
            'Hot Kashaya' => [
                'Shunti Kashaya',
                'Masala Kashaya',
                'Horse Gram Kashaya',
                'Malnad Kashaya',
            ],
            'Lassi' => [
                'Sweet Lassi',
                'Dry Fruit Lassi',
                'Pista Lassi',
                'Rose Lassi',
                'Salt Lassi',
            ],
            'Special Variety Juices' => [
                'Cream Fruit Punch',
                'Anar Musambi',
                'Apple Bowl',
                'Arabian Dry Fruit Milkshake',
                'Caramello Popcorn Milkshake',
                'Dubai Dates',
                'Ferrero Rocher',
                'Fig & Honey',
                'Guava Bowl',
                'Jamboo Jamoon Juice (Seasonal)',
                'Jigarthanda',
                'Kit Kat Milkshake',
                'Mango Dry Fruit',
                'Nariyal Punch',
                'Orange Bowl (Seasonal)',
                'Orange Punch',
                'Pulpy Musambi Punch',
            ],
            'Soups' => [
                'Tomato Soup',
                'Vegetable Soup',
                'Mushroom Soup',
                'Bonda Soup',
                'Corn Soup',
                'Sweet Corn Soup',
                'Pineapple Soup',
            ],
            'Chats' => [
                'Masala Puri',
                'Bhel Puri',
                'Pani Puri',
                'Aloo Puri',
                'Sev Puri',
                'Dahi Puri',
                'Kachori',
                'Cutlet',
                'Samosa Masala',
                'Nippattu Masala',
                'Nimbu Masala',
            ],
            'Holige' => [
                'Coconut Holige',
                'Kova Holige',
                'Carrot Holige',
                'Anjoor Holige',
                'Kobbari Holige',
                'Bele Holige',
            ],
            'South Indian Sweets' => [
                'Peni',
                'Chiroti',
                'Ladoo',
                'Badam Puri',
                'Jamoon',
                'Chandrahara',
                'Jahangeer',
                'Jalebi',
                'Mysore Pak',
                'Badusha',
                'Cashew Burfi',
                'Badam Burfi',
                'Boondi Burfi',
                'Fruit Burfi',
                'Pista Burfi',
                'Chocolate Burfi',
                'Dry Fruit Chocolate Burfi',
                'Shavige Burfi',
                'Anjoor Burfi',
                'Khova Burfi',
                'Ice Cream Burfi',
                'Badam Pan',
                'Mango Kathli',
                'Sohan Papdi',
                'Mandige',
                'Badam Halwa',
                'Mango Roll',
                'Kaju Samosa',
                'Kaju Roll',
                'Almond Roll',
                'Khova Jahangeer',
                'Pista Roll',
                'Chandrakala',
                'Mohan Ladoo',
            ],
            'Payasa' => [
                'ಗೋದಿ ಪಾಯಸ',
                'ಅಪ್ಪೆ ಪಾಯಸ',
                'ಶಾವಿಗೆ ಪಾಯಸ',
                'ಪಾಲ್ ಪಾಯಸ',
            ],
            'Pickles' => [
                'ಮಾವಿನಕಾಯಿ',
                'ನಿಂಬೆಹಣ್ಣು',
            ],
            'Kosambari' => [
                'ಕಡಲೆಬೇಳೆ',
                'ಹೆಸರುಬೇಳೆ',
                'ಮೊಳಕೆ ಹೆಸರುಕಾಳು',
                'ಸ್ವೀಟ್ ಕಾರ್ನ್',
                'ಫ್ರೂಟ್',
                'ಕ್ಯಾರೆಟ್',
                'ಮಿಕ್ಸ್ ವೆಜ್',
            ],
            'Palya' => [
                'ಬೀನ್ಸ್',
                'ಅಲಸಂದೆ',
                'ತೊಂಡೆಕಾಯಿ',
                'ಆಲೂಗಡ್ಡೆ',
                'ಕೋಸು',
                'ಮಿಕ್ಸ್ ವೆಜ್',
                'ಸೋಮೆ ಬದನೆಕಾಯಿ',
            ],
            'Bath' => [
                'ಚಿತ್ರಾನ್ನ',
                'ಪುಳಿಯೋಗರೆ',
                'ವಾಂಗಿ ಬಾತ್',
                'ತುಪ್ಪದ ಅನ್ನ',
                'ನಿಂಬು ಚಿತ್ರಾನ್ನ',
                'ಮಾವಿನಕಾಯಿ ಚಿತ್ರಾನ್ನ',
                'ಕಾಯಿ ಸಾಸಿವೆ',
                'ವೆಜ್ ಪಲಾವ್',
            ],
            'Tove' => [
                'ತೊಗರಿ ಬೇಳೆ',
                'ತೊಗರಿ ಬೇಳೆ + ಸೊಪ್ಪು',
                'ತೊಗರಿ ಬೇಳೆ + ಮಾವಿನಕಾಯಿ',
            ],
            'Happala' => [
                'ಉದ್ದಿನ ಹಪ್ಪಳ',
                'ಅಕ್ಕಿ ಹಪ್ಪಳ',
                'ಟೊಮ್ಯಾಟೊ ಹಪ್ಪಳ',
                'ಖಾರ ಹಪ್ಪಳ',
                'ಬೇಬಿ ಹಪ್ಪಳ',
            ],
            'Sandige' => [
                'ಅರಳು ಸಂಡಿಗೆ',
                'ಸಬ್ಬಕ್ಕಿ ಸಂಡಿಗೆ',
                'ಪೇಣಿ ಸಂಡಿಗೆ',
            ],
            'Huli' => [
                'ಕೂಟು',
                'ಬೂದುಗುಂಬಳ',
                'ಮಜ್ಜಿಗೆ ಹುಳಿ',
                'ಸಂಡಿಗೆ ಹುಳಿ',
                'ಹುಳಿ ತೊವೆ',
                'ತರಕಾರಿ ಹುಳಿ',
            ],
            'Saaru' => [
                'ಕೆಂಪು ಸಾರು',
                'ನಿಂಬು ಸಾರು',
                'ಜೀರಿಗೆ ಮೆಣಸು ಸಾರು',
                'ಅಪ್ಪೆ ಸಾರು',
            ],
            'Tambuli' => [
                'ಶುಂಠಿ ತಂಬುಳಿ',
                'ಜೀರಿಗೆ ತಂಬುಳಿ',
                'ಸೌತೆಕಾಯಿ ರಾಯ್ತಾ',
            ],
            'Khara' => [
                'ಅಂಬೋಡೆ',
                'ಆಲೂ ಬೋಂಡ',
                'ಹೀರೆಕಾಯಿ ಬಜ್ಜಿ',
                'ಮೆಣಸಿನಕಾಯಿ ಬಜ್ಜಿ',
                'ನುಚ್ಚಿನ ಉಂಡೆ',
            ],
            'Bengali Sweets' => [
                'Angoor Malai',
                'Angoor Chum-Chum',
                'Angoor Rasamalai',
                'Soup Angoor Rabadi',
                'Chum-Chum',
                'Karijura Burfy',
                'Rasamalai',
                'Champarkali',
                'Malai Gulla',
                'Rasagulla',
                'Raj Bhog',
                'Hony Dew',
                'Cream Toast',
                'China Cross',
                'Glass Sandwich',
                'Peta Sandwich',
                'Rasamanjari',
                'Bread Rasamanjari',
                'Ajmeer Kalakhana',
                'Keer Mohan',
                'Dry Fruits Sandwich',
                'Sandesh Roll',
            ],
            'Indian Breads' => [
                'Channa Batura',
                'Poori',
                'Methi Chapathi + Kulcha',
                'Bread Roast',
                'Masala Kulcha',
                'Alu Parotha',
                'White Holige',
                'Akki Roti',
                'Coi Parata',
                'Mallain Nan',
                'Parotha',
                'Bili Holige',
            ],
            'Dosa & Idly' => [
                'Onion Dosa',
                'Sat Dosa',
                'Rava Dosa',
                'Bullet Idly',
                'Sagu Masala',
                'Tomato Dosa',
                'Akki Idly',
                'Rava Idly',
                'Tatte Idly',
                'Mallige Idly',
            ],
            'Roti' => [
                'Romali Roti',
                'Methi Roti',
                'Kulcha',
                'Stuffed Kulcha',
                'Pineapple Romali',
                'Kesari Romali',
                'Masala Parota',
                'Dokla',
                'Butter Naan',
            ],
            'North Indian Side Dishes' => [
                'Paneer Butter Masala',
                'Channa Masala',
                'Shahi Kurma',
                'Veg. Kadai',
                'Veg. Hyderabad',
                'Green Peas Masala',
                'Plain Gravy',
                'Alu Rajima',
                'Alu Gobi',
            ],
        ];

        foreach ($menu as $category => $items) {
            foreach ($items as $item) {
                MenuItem::firstOrCreate(
                    ['name' => $item, 'category' => $category],
                    [
                        'traditional_name' => null,
                        'description' => '',
                        'ingredients' => [],
                        'image' => '',
                        'is_popular' => in_array($item, $popular),
                        'sattvic_grade' => '100% Pure Sattvic (No Onion/Garlic)',
                    ]
                );
            }
        }
    }
}
